### ISSUE TITLE
Getting ERR_CONNECTION-REFUSED error

### ISSUE THREAD

**Issue by sonnyk22** [DanWahlin/Angular-Core-Concepts#4]
Thank you for this repo. It has helped me a lot with learning Docker, and by watching your great courses on Pluralsight.

After running the `docker-compose`, everything works great on my Host laptop (Windows 10), however when I browse to the same app from another laptop (Mac) that I have at home (both running in my home network), the `Angular `and `Nginx `works fine, but the `Angular `cannot connect to `Node api `container. I get ERR_CONNECTION-REFUSED error as show below.

![err](https://user-images.githubusercontent.com/6744710/82167273-45f75500-9889-11ea-87c6-6a4f0fcf517f.png)

Have you seen this type of error before?

Thank you

**Comment by DanWahlin** [comment]
Glad to hear the project helped.

I'm surprised you were able to get to anything from a different machine. Normally localhost is only available on the local machine (unless something else was changed configuration-wise). I haven't tried it within a home network in a long time though. Since I'm surprised localhost is working at all across machines, my guess is that there's a firewall issue or something related blocking the port given the "ERR_CONNECTION_REFUSED" error. Hard to say though. I'm happy to help with code issues, but I hack my way around network issues since that's not my speciality. Wish I had more info for you on that.
